---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: jekyll-posts
  label: Trade Explained
  create: all
  templates:
  - trade-explained
  - video
  - external-commentary
- type: directory
  path: _podcast
  label: Podcast
  create: all
  match: "**/*"
  templates:
  - podcast
- type: directory
  path: _series
  label: Series
  create: all
  match: "**/*"
  templates:
  - series
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - author
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
